# Generated by Django 3.1.7 on 2021-04-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_text',
        ),
        migrations.RenameField(
            model_name='ref',
            old_name='color',
            new_name='color_text',
        ),
    ]
